name: midtrans_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.3.0
  dio: 4.0.6
  firebase_messaging: 14.1.2
  shared_preferences: 2.0.15
  flutter_screenutil: 5.6.0
  flutter_spinkit: 5.1.0
  iconly: 1.0.1
  intl: 0.17.0
  pattern_formatter: 2.0.0
  midpay: ^1.1.7
  url_launcher: 6.1.7
  flutter: 
    sdk: flutter
  firebase_dynamic_links: ^5.0.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

